serenity.project.name = harp-demo-screenplay-mobile
serenity.test.root = com.harp.demo.screenplay
serenity.outputDirectory = target/site/serenity
serenity.take.screenshots = AFTER_EACH_STEP

webdriver.driver = appium
appium.hub = http://127.0.0.1:4723/
appium.platformName = Android
appium.process.desired.capabilities = true
appium.additional.capabilities = app,appActivity,appPackage,autoGrantPermissions,automationName,deviceName,newCommandTimeout,noReset,udid
